name: Close incomplete issue templates
on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  close-issues-if-invalid:
    runs-on: ubuntu-latest
    steps:
      - uses: queengooborg/invalid-issue-closer@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "invalid :no_entry_sign:"
          comment: |
            This issue was automatically closed because the template has not been properly filled out. A summary has not been added to the title of the issue.

            If this has been closed in error, edit the title and/or body, and post a follow-up comment.
          normalize-newlines: true
          title-contains: "<SUMMARIZE THE PROBLEM>"
