# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ ] # Test on push to every branch
  pull_request:
    branches: [ ] # Test on push to every branch

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        FORCE_COLOR: 3

  # This succeeds if all the matrix builds succeed. This allows us to set branch
  # protection rules on this job in particular, rather than having to change
  # branch protection rules when the matrix changes. See
  # https://github.community/t/status-check-for-a-matrix-jobs/127354/7.
  testall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test (matrix)
    needs: test
    steps:
      - name: Check test matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
