# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ ] # Test on push to every branch
  pull_request:
    branches: [ ] # Test on push to every branch

jobs:
  maintenance_lts:
    name: "Node.js maintenance LTS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 10.x
    - run: npm install
    - run: npm test
      env:
        FORCE_COLOR: 3

  active_lts:
    name: "Node.js active LTS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x
    - run: npm install
    - run: npm test
      env:
        FORCE_COLOR: 3
