name: Ping other repos

on:
  push:
    branches: [main]

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SIDESHOWBARKER_TOKEN: ${{ secrets.SIDESHOWBARKER }}
    if: ${{ github.respository == 'mdn/browser-compat-data' && env.SIDESHOWBARKER_TOKEN != '' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SIDESHOWBARKER }}
          event-type: ping
