name: "PR Needs Rebase"
on:
  push:
  pull_request_target:
    types: [synchronize]

jobs:
  idle:
    uses: mdn/workflows/.github/workflows/pr-rebase-needed.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
