name: 'PR Needs Rebase'
on:
  push:
  pull_request_target:
    types: [synchronize]

permissions:
  contents: read

jobs:
  idle:
    permissions:
      contents: none
    uses: mdn/workflows/.github/workflows/pr-rebase-needed.yml@main
    with:
      target-repo: "mdn/browser-compat-data"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
